server:
  port: 9000
  context-path: /beerhouse
datasource:
  url: jdbc:h2:~/beerhouse
  username: sa
  password:
  driver-class-name: org.h2.Driver
liquibase:
  enabled: true
  change-log: classpath:db/db.changelog-master.xml
spring:
  jpa:
    show-sql: true



